# services/java/message-logic-service/src/main/resources/application.yml
server:
  port: 8082 # Port for Message Logic service (internal in Docker network)

spring:
  application:
    name: message-logic-service
  h2:
    console:
      enabled: true # Enable H2 console for testing (optional)
      path: /h2-console
  datasource: # H2 in-memory configuration
    url: jdbc:h2:mem:messagedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  kafka: # Basic Kafka configuration (will be expanded later)
    bootstrap-servers: kafka:9092 # Connects to our Dockerized Kafka service
  eureka:
    client:
      enabled: false # Temporarily disable Eureka client for Day 3
    instance:
      hostname: message-logic-service