# services/python/ai-chat-service/config.yaml
# This file defines default application settings.
# Values here can be overridden by environment variables for dynamic deployment.

app_settings:
  debug_mode: true      # Enable Flask debug mode for development
  port: 5000            # Default port for the Flask application
  host: 0.0.0.0         # Default host for the Flask application (0.0.0.0 for Docker)
  log_level: INFO       # Default logging level (INFO, DEBUG, WARNING, ERROR)

# MongoDB configuration defaults (non-sensitive details like host, port, db name)
# Sensitive credentials (username, password) are handled ONLY by environment variables for security.
mongodb:
  host: mongodb         # Docker service name for MongoDB (resolves internally in Docker network)
  port: 27017           # Default MongoDB port
  db_name: ai_chat_db   # Default database name for this service